import {t} from './services__i18n.js?v=7.9.4.139-ledger-print';
import {createPortal} from 'react-dom';
import { SearchableDropdown } from './components__common__Dropdown.js?v=7.9.4.139-ledger-print';
import React,{useState,useEffect,useRef} from 'react';
import {useApp} from './context__AppContext.js?v=7.9.4.139-ledger-print';
import {PaymentModal} from './components__pos__PaymentModal.js?v=7.9.4.139-ledger-print';
import {Plus,Minus,Trash2,PauseCircle,Clock,Package,Tag} from 'lucide-react';
const h=React.createElement;
export function DesktopCheckout(){
 const app=useApp();const {cart,settings,updateCartItemQuantity,updateCartItemPrice,updateCartItemScaleAmount,updateCartItemUnit,removeFromCart,holdCurrentInvoice,clearCart,setShowHoldInvoicesModal,heldInvoices,invoiceAdditionalCharges,setInvoiceAdditionalCharges}=app;
 const [accountContainer,setAccountContainer]=useState(null);
 const [toolsTarget,setToolsTarget]=useState(null);
 useEffect(()=>setToolsTarget(document.getElementById('ct-item-tools-target')),[]);
 const [selected,setSelected]=useState(null);const root=useRef(null);
 const key=i=>`${i.productId}-${i.unitId}`;
 const item=cart.find(i=>key(i)===selected);
 useEffect(()=>{root.current?.querySelector('.ct-row-selected')?.scrollIntoView({block:'nearest'})},[selected]);
 useEffect(()=>{if(!cart.some(i=>key(i)===selected))setSelected(cart.length?key(cart[0]):null)},[cart,selected]);
 useEffect(()=>{const down=e=>{if(e.defaultPrevented||!window.matchMedia('(min-width:1024px)').matches||!item||e.ctrlKey||e.altKey||e.metaKey||e.target.closest('input,textarea,select,[contenteditable="true"]')||document.querySelector('#modal-payment-backdrop,#full-cart-modal-backdrop,[role="dialog"],.ct-nav-menu,.ct-action-shield,.cash-action-menu'))return;if(['+','-','ArrowUp','ArrowDown','PageUp','PageDown','Delete'].includes(e.key)){e.preventDefault();if(e.key==='Delete')removeFromCart(item.productId,item.unitId);else if(e.key==='+'||e.key==='-')updateCartItemQuantity(item.productId,item.unitId,Number(item.quantity)+(e.key==='+'?1:-1));else {const index=cart.findIndex(i=>key(i)===key(item));const next=Math.max(0,Math.min(cart.length-1,index+(['ArrowUp','PageUp'].includes(e.key)?-1:1)*(e.key.startsWith('Page')?6:1)));setSelected(key(cart[next]));}}};window.addEventListener('keydown',down);return()=>window.removeEventListener('keydown',down)},[item,cart,updateCartItemQuantity,removeFromCart]);
 const button=(label,Icon,fn,disabled=false)=>h('button',{type:'button',onClick:fn,disabled},h(Icon,{size:16}),t(label));
 const field=(label,child)=>h('label',null,h('span',null,t(label)),child);
 const controls=h('div',{className:'ct-data-controls'},h('div',{className:'ct-section-title'},h(Package,{size:17}),t("البيانات"),item&&button('',Trash2,()=>removeFromCart(item.productId,item.unitId))),item?h('div',{className:'ct-item-fields'},field('اسم الصنف',h('input',{readOnly:true,value:item.productName})),field('الكمية',h('div',{className:'ct-quantity-stepper'},button('',Plus,()=>updateCartItemQuantity(item.productId,item.unitId,Number(item.quantity)+1)),h('input',{'aria-label':t("الكمية"),type:'number',min:0.001,step:'any',value:item.quantity,onChange:e=>{const n=Number(e.target.value);if(n>0)updateCartItemQuantity(item.productId,item.unitId,n)}}),button('',Minus,()=>updateCartItemQuantity(item.productId,item.unitId,Number(item.quantity)-1)))),h(SearchableDropdown,{id:'cashier-unit',label:t("الوحدة"),options:(item.availableUnits||[]).map(u=>({id:u.id,label:u.name})),selectedId:item.unitId,onSelect:id=>{updateCartItemUnit(item.productId,item.unitId,id);setSelected(`${item.productId}-${id}`)}}),field(settings.scaleModeEnabled?'المبلغ':'السعر',h('input',{type:'number',min:0,step:'any',value:settings.scaleModeEnabled?Number((item.quantity*item.unitPrice).toFixed(2)):item.unitPrice,onChange:e=>{if(e.target.value==='')return;const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0)(settings.scaleModeEnabled?updateCartItemScaleAmount:updateCartItemPrice)(item.productId,item.unitId,n)}}))):h('p',null,t("اختر صنفاً من السلة")));
 const footerControls=h('div',{className:'ct-footer-tools'},h('div',{className:'ct-operation-actions'},button('تعليق',PauseCircle,()=>holdCurrentInvoice(),!cart.length),button(`المعلقة (${heldInvoices.length})`,Clock,()=>setShowHoldInvoicesModal(true)),button('تفريغ',Trash2,()=>{if(confirm('تفريغ جميع أصناف السلة؟'))clearCart()},!cart.length)));
 const customers=(app.customers||[]).filter(c=>!c.deletedAt);
 const cartPanel=h('section',{className:'ct-products-cart','aria-label':t("منتجات الفاتورة")},h('div',{className:'ct-cart-title'},h('label',{className:'ct-outlined-field'},h('span',null,t("تكلفة إضافية")),h('input',{'aria-label':t("تكلفة إضافية"),type:'number',min:0,step:'any',value:invoiceAdditionalCharges,onChange:e=>setInvoiceAdditionalCharges(Math.max(0,Number(e.target.value)||0))})),h(SearchableDropdown,{id:'cart-customer',label:t("العميل"),onQuickAdd:()=>window.dispatchEvent(new CustomEvent('ct-quick-customer')),quickAddLabel:'+ عميل',options:[{id:'cust-walkin',label:t("عميل نقدي")},...customers.filter(c=>c.id!=='cust-walkin').map(c=>({id:c.id,label:c.name}))],selectedId:app.selectedCustomer?.id,onSelect:id=>app.setSelectedCustomer(customers.find(c=>c.id===id)||{id:'cust-walkin',name:'عميل نقدي',balance:0,isVirtual:true})}),h('div',{id:'ct-invoice-notes-target'})),h('div',{className:'ct-cart-columns'},...['#','اسم الصنف','الوحدة','الكمية','السعر','الإجمالي'].map(t=>h('span',{key:t},t))),h('div',{className:'ct-cart-rows',tabIndex:0,'aria-label':t("منتجات الفاتورة")},...cart.map((i,index)=>h('button',{type:'button',key:key(i),className:`ct-cart-row ${item&&key(item)===key(i)?'ct-row-selected':''}`,onClick:()=>setSelected(key(i))},h('span',{className:'ct-row-number'},index+1),h('strong',null,i.productName),h('span',null,i.unitName),h('span',null,i.quantity),h('span',null,Number(i.unitPrice).toFixed(2)),h('b',null,Number(i.quantity*i.unitPrice).toFixed(2)))),!cart.length&&h('div',{className:'ct-cart-empty'},h(Package,{size:28}),h('strong',null,t("ابدأ فاتورة جديدة")))));
 return h('div',{className:'ct-desktop-checkout',ref:root},toolsTarget&&createPortal(h('div',{className:'ct-top-item-tools'},controls,h('div',{id:'ct-payment-account-target',ref:setAccountContainer}),footerControls),toolsTarget),cartPanel,h('aside',{className:'ct-checkout-rail'},h(PaymentModal,{embedded:true,isOpen:true,accountContainer,onSuccess:()=>{},onClose:()=>{}})));
}
