import React,{useState,useEffect} from 'react';
import {createPortal} from 'react-dom';
import {MoreVertical,Eye,Edit,Trash2,X,Package} from 'lucide-react';
import {useApp} from './context__AppContext.js?v=7.9.4.134-invoice-filters';
import {ModalLayer} from './components__common__ModalLayer.js?v=7.9.4.134-invoice-filters';
const h=React.createElement;
export function ProductActions({product,onEdit,onDelete}){
 const {settings,categories,getProductStock}=useApp();const [menu,setMenu]=useState(null);const [view,setView]=useState(false);
 useEffect(()=>{if(!menu&&!view)return;const key=e=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setMenu(null);setView(false)}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[menu,view]);
 const close=e=>{e.preventDefault();e.stopPropagation();setMenu(null)};
 const field=(label,value)=>h('div',{className:'ct-info-field'},h('span',null,label),h('strong',null,value??'—'));
 return h(React.Fragment,null,h('button',{type:'button',className:'ct-product-more','aria-label':`إجراءات ${product.name}`,'aria-expanded':!!menu,onClick:e=>{e.stopPropagation();const r=e.currentTarget.getBoundingClientRect();setMenu({top:Math.max(8,Math.min(r.bottom+5,window.innerHeight-150)),left:Math.max(8,Math.min(r.right-180,window.innerWidth-188))})}},h(MoreVertical,{size:18})),menu&&createPortal(h('div',{className:'ct-action-shield',onPointerDown:e=>{if(e.target===e.currentTarget){e.preventDefault();e.stopPropagation()}},onClick:close},h('div',{className:'cash-action-menu ct-product-actions-menu',style:{position:'fixed',...menu,width:180},onClick:e=>e.stopPropagation(),onPointerDown:e=>e.stopPropagation()},h('button',{type:'button',onClick:()=>{setMenu(null);setView(true)}},h(Eye,{size:16}),'عرض المعلومات'),h('button',{type:'button',onClick:()=>{setMenu(null);onEdit?.(product)}},h(Edit,{size:16}),'تعديل'),h('button',{type:'button',className:'danger',onClick:()=>{setMenu(null);if(confirm(`حذف الصنف «${product.name}» ونقله للمحذوفات؟`))onDelete?.(product.id)}},h(Trash2,{size:16}),'حذف'))),document.body),view&&h(ModalLayer,{className:'fixed inset-0 flex items-center justify-center p-4 bg-black/50',role:'dialog','aria-modal':true,onClick:e=>{e.stopPropagation();if(e.target===e.currentTarget)setView(false)}},h('section',{className:'ct-product-info',onClick:e=>e.stopPropagation()},h('header',null,h(Package,{size:22}),h('div',null,h('small',null,'معلومات الصنف'),h('h3',null,product.name)),h('button',{type:'button',onClick:()=>setView(false),'aria-label':'إغلاق'},h(X,{size:18}))),h('div',{className:'ct-info-grid'},field('التصنيف',categories.find(c=>c.id===product.categoryId)?.name),field('المخزون',getProductStock(product.id,settings.activeWarehouseId)),field('كود الصنف',product.sku||product.internalCode),field('العلامة التجارية',product.brand),field('الموقع',product.location),field('حد إعادة الطلب',product.reorderPoint),field('الصلاحية',product.expiryDate),field('ملاحظات',product.notes||product.description)),h('div',{className:'ct-unit-details'},...(product.units||[]).map(u=>h('div',{key:u.id},h('strong',null,u.name),h('span',null,`بيع: ${Number(u.salePrice||0).toFixed(2)} ${settings.currencySymbol}`),h('span',null,`شراء: ${Number(u.costPrice||0).toFixed(2)} ${settings.currencySymbol}`),h('small',null,`الباركود: ${(u.barcodes||[]).join('، ')||'—'}`)))))));
}
