(function(){
'use strict';
let products=[],recipes=[],orders=[],stores=[];
const $=id=>document.getElementById(id);
const branchId=()=>window.Cashtop?.branchIdFromSession?.()||'MAIN';
const readArray=key=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:Object.values(value||{})}catch(_){return[]}};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const num=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const precise=value=>num(value).toFixed(3).replace(/\.?0+$/,'')||'0';
const money=value=>num(value).toFixed(3).replace(/0+$/,'').replace(/\.$/,'')+' ₪';
function openModal(id){$(id)?.classList.add('active')}
function closeModal(id){$(id)?.classList.remove('active');closeSuggestions()}
function productById(id){return products.find(product=>String(product.id)===String(id))}
function productByName(name){const normalized=String(name||'').trim().toLowerCase();return products.find(product=>String(product.name||'').trim().toLowerCase()===normalized)}
function pName(id,fallback='منتج محذوف'){return productById(id)?.name||fallback}
function warehouseName(id){if(String(id)==='shop')return branchId()==='MAIN'?'الفرع الرئيسي (الأصلي)':'رصيد الفرع الحالي';return stores.find(store=>String(store.id)===String(id))?.name||'مخزن محذوف'}
function branchQty(product){if(branchId()==='MAIN')return num(product.stockPieces);return num(product.branchStocks?.[branchId()])}
function getQty(product,warehouseId){if(!product)return 0;if(String(warehouseId)==='shop')return branchQty(product);return num(product.storeStocks?.[warehouseId])}
function setQty(product,warehouseId,value){const qty=Math.max(0,num(value));if(String(warehouseId)==='shop'){if(branchId()==='MAIN')product.stockPieces=qty;else{product.branchStocks=product.branchStocks&&typeof product.branchStocks==='object'?product.branchStocks:{};product.branchStocks[branchId()]=qty}}else{product.storeStocks=product.storeStocks&&typeof product.storeStocks==='object'?product.storeStocks:{};product.storeStocks[warehouseId]=qty}}
function changeQty(product,warehouseId,delta){setQty(product,warehouseId,getQty(product,warehouseId)+num(delta))}
function warehouseOptions(selected='shop'){return `<option value="shop" ${String(selected)==='shop'?'selected':''}>${esc(warehouseName('shop'))}</option>`+stores.map(store=>`<option value="${esc(store.id)}" ${String(selected)===String(store.id)?'selected':''}>${esc(store.name)}</option>`).join('')}
function closeSuggestions(except=null){document.querySelectorAll('.suggestions.open').forEach(box=>{if(box!==except)box.classList.remove('open')})}
function showSuggestions(input,hidden,box,query=''){
 const q=String(query||'').trim().toLowerCase();
 const matches=products.filter(product=>!q||String(product.name||'').toLowerCase().includes(q)||String(product.barcode||product.pieceBarcode||'').includes(q)).slice(0,12);
 box.innerHTML=matches.length?matches.map(product=>`<div class="suggestion" data-id="${esc(product.id)}"><b>${esc(product.name)}</b><small>المخزون: ${precise(branchQty(product))} | التكلفة: ${money(product.cost)} | الباركود: ${esc(product.barcode||product.pieceBarcode||'-')}</small></div>`).join(''):'<div class="suggestion"><b>لا يوجد تطابق</b><small>اترك الاسم المكتوب لإنشاء منتج مصنع جديد.</small></div>';
 closeSuggestions(box);box.classList.add('open');
 box.querySelectorAll('[data-id]').forEach(item=>item.addEventListener('mousedown',event=>{event.preventDefault();const product=productById(item.dataset.id);if(!product)return;input.value=product.name;hidden.value=product.id;box.classList.remove('open');if(input.id==='finishedProductName'){finishedBarcode.value=product.barcode||product.pieceBarcode||'';finishedSalePrice.value=num(product.pricePiece??product.price);updateRecipePreview()}}));
}
function bindAutocomplete(input,hidden,box){
 input.addEventListener('input',()=>{const exact=productByName(input.value);hidden.value=exact?.id||'';showSuggestions(input,hidden,box,input.value);updateRecipePreview()});
 input.addEventListener('focus',()=>showSuggestions(input,hidden,box,input.value));
 input.addEventListener('blur',()=>setTimeout(()=>box.classList.remove('open'),150));
}
function createIngredientRow(item={}){
 const row=document.createElement('div');row.className='ingredient-row';
 const product=productById(item.productId);const output=num(item.legacyOutputQty,1);const qty=item.convertLegacy?num(item.qty)/Math.max(.001,output):num(item.qty??item.qtyPerUnit,1);
 row.innerHTML=`<div class="autocomplete"><input type="hidden" class="ingredient-product-id" value="${esc(product?.id||item.productId||'')}"><input class="form-control ingredient-product-name" autocomplete="off" placeholder="اكتب اسم المادة الخام" value="${esc(product?.name||item.name||'')}"><div class="suggestions"></div></div><div><input class="form-control ingredient-qty" type="number" min="0.000001" step="0.001" value="${precise(qty)}" oninput="updateRecipePreview()"><span class="field-help">كمية المادة لكل قطعة منتجة</span></div><button type="button" class="action-btn delete" title="حذف المادة"><i class="fa-solid fa-trash"></i></button>`;
 const input=row.querySelector('.ingredient-product-name'),hidden=row.querySelector('.ingredient-product-id'),box=row.querySelector('.suggestions');bindAutocomplete(input,hidden,box);row.querySelector('.delete').addEventListener('click',()=>{row.remove();updateRecipePreview()});return row;
}
function addIngredient(item={}){$('ingredients').appendChild(createIngredientRow(item));updateRecipePreview()}
function collectIngredients(){return [...document.querySelectorAll('.ingredient-row')].map(row=>{const input=row.querySelector('.ingredient-product-name'),exact=productByName(input.value);const productId=row.querySelector('.ingredient-product-id').value||exact?.id||'';return{productId,name:input.value.trim(),qty:num(row.querySelector('.ingredient-qty').value)}}).filter(item=>item.productId&&item.qty>0)}
function recipeTotals(recipeLike={}){
 const ingredients=recipeLike.ingredients||collectIngredients();const output=Math.max(.001,num(recipeLike.outputQty??$('outputQty')?.value,1));
 const ingredientMode=recipeLike.ingredientMode||'perUnit';
 const rawPerUnit=ingredients.reduce((sum,item)=>{const qtyPerUnit=ingredientMode==='perUnit'?num(item.qty):num(item.qty)/output;return sum+num(productById(item.productId)?.cost)*qtyPerUnit},0);
 const overhead=Math.max(0,num(recipeLike.overheadCost??$('overheadCost')?.value));const total=rawPerUnit*output+overhead;const unitCost=total/output;
 const salePrice=Math.max(0,num(recipeLike.salePrice??$('finishedSalePrice')?.value??productById(recipeLike.finishedProductId)?.pricePiece));const revenue=salePrice*output;
 return{rawPerUnit,overhead,total,unitCost,salePrice,revenue,profit:revenue-total,unitProfit:salePrice-unitCost,output};
}
function updateRecipePreview(){const totals=recipeTotals();if(!$('recipePreview'))return;$('recipePreview').innerHTML=`<div class="preview-line"><span>تكلفة المواد للقطعة</span><b>${money(totals.rawPerUnit)}</b></div><div class="preview-line"><span>تكلفة الدورة كاملة</span><b>${money(totals.total)}</b></div><div class="preview-line"><span>تكلفة القطعة المصنعة</span><b>${money(totals.unitCost)}</b></div><div class="preview-line"><span>سعر البيع</span><b>${money(totals.salePrice)}</b></div><div class="preview-line"><span>ربح القطعة المتوقع</span><b class="${totals.unitProfit>=0?'success':'danger'}">${money(totals.unitProfit)}</b></div>`}
function generateBarcode(){const base=('729'+Date.now().toString().slice(-8)+Math.floor(Math.random()*10)).slice(0,12);let sum=0;[...base].forEach((digit,index)=>{sum+=Number(digit)*(index%2===0?1:3)});return base+((10-(sum%10))%10)}
function generateFinishedBarcode(){$('finishedBarcode').value=generateBarcode()}
function ensureFinishedProduct(){
 const name=$('finishedProductName').value.trim();if(!name)throw new Error('اكتب اسم المنتج المصنع.');let product=productById($('finishedProductId').value)||productByName(name);
 const barcode=$('finishedBarcode').value.trim();const duplicate=barcode&&products.find(item=>String(item.id)!==String(product?.id||'')&&[item.barcode,item.pieceBarcode,item.unitBarcode].some(value=>String(value||'')===barcode));if(duplicate)throw new Error(`الباركود مستخدم للمنتج: ${duplicate.name}`);
 const salePrice=Math.max(0,num($('finishedSalePrice').value));const now=new Date().toISOString();
 if(!product){product={id:`MFGP_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name,barcode,pieceBarcode:barcode,unitBarcode:'',addType:'piece',pieceName:'قطعة',unitName:'وحدة',piecesPerUnit:1,stockPieces:0,branchStocks:{},storeStocks:{},cost:0,pricePiece:salePrice,price:salePrice,salePrice,active:true,generatedByManufacturing:true,category:'منتجات مصنعة',createdAt:now,updatedAt:now};products.push(product)}else{product.name=name;product.barcode=barcode||product.barcode||'';product.pieceBarcode=barcode||product.pieceBarcode||'';product.pricePiece=salePrice;product.price=salePrice;product.salePrice=salePrice;product.active=product.active!==false;product.updatedAt=now}
 $('finishedProductId').value=product.id;return product;
}
function load(){products=readArray('cashtop_products');recipes=readArray('cashtop_manufacturing_recipes');orders=readArray('cashtop_manufacturing_orders');stores=readArray('cashtop_stores').filter(store=>!store.branchId||String(store.branchId)===String(branchId())||branchId()==='MAIN');$('sourceWarehouse').innerHTML=warehouseOptions();$('destinationWarehouse').innerHTML=warehouseOptions();renderAll()}
function openRecipe(){document.querySelector('#recipeModal form').reset();$('recipeId').value='';$('finishedProductId').value='';$('ingredients').innerHTML='';$('sourceWarehouse').innerHTML=warehouseOptions();$('destinationWarehouse').innerHTML=warehouseOptions();$('outputQty').value='1';$('overheadCost').value='0';$('finishedSalePrice').value='0';addIngredient();updateRecipePreview();openModal('recipeModal')}
function saveRecipe(event){event.preventDefault();try{const finished=ensureFinishedProduct();const ingredients=collectIngredients();if(!ingredients.length)throw new Error('أضف مادة خام واحدة على الأقل واخترها من الاقتراحات.');if(ingredients.some(item=>String(item.productId)===String(finished.id)))throw new Error('لا يمكن أن يكون المنتج النهائي مادة خام لنفسه.');const id=$('recipeId').value||`REC_${Date.now()}_${Math.random().toString(36).slice(2,5)}`;const recipe={id,branchId:branchId(),finishedProductId:finished.id,finishedProductName:finished.name,finishedBarcode:finished.barcode||'',salePrice:num(finished.pricePiece),outputQty:Math.max(.001,num($('outputQty').value,1)),sourceWarehouseId:$('sourceWarehouse').value,destinationWarehouseId:$('destinationWarehouse').value,overheadCost:Math.max(0,num($('overheadCost').value)),notes:$('recipeNotes').value.trim(),ingredientMode:'perUnit',ingredients,updatedAt:new Date().toISOString()};const index=recipes.findIndex(item=>String(item.id)===String(id));if(index>=0)recipes[index]=recipe;else recipes.push(recipe);localStorage.setItem('cashtop_products',JSON.stringify(products));localStorage.setItem('cashtop_manufacturing_recipes',JSON.stringify(recipes));closeModal('recipeModal');load();Cashtop.showToast('تم حفظ المنتج المصنع والوصفة وإضافتهما للمخزون والكاشير.','success')}catch(error){Cashtop.showToast(error.message||'تعذر حفظ الوصفة.','error')}}
function editRecipe(id){const recipe=recipes.find(item=>String(item.id)===String(id));if(!recipe)return;const product=productById(recipe.finishedProductId);$('recipeId').value=recipe.id;$('finishedProductId').value=recipe.finishedProductId;$('finishedProductName').value=product?.name||recipe.finishedProductName||'';$('finishedBarcode').value=product?.barcode||product?.pieceBarcode||recipe.finishedBarcode||'';$('finishedSalePrice').value=num(product?.pricePiece??product?.price??recipe.salePrice);$('outputQty').value=num(recipe.outputQty,1);$('sourceWarehouse').innerHTML=warehouseOptions(recipe.sourceWarehouseId||'shop');$('destinationWarehouse').innerHTML=warehouseOptions(recipe.destinationWarehouseId||'shop');$('overheadCost').value=num(recipe.overheadCost);$('recipeNotes').value=recipe.notes||'';$('ingredients').innerHTML='';recipe.ingredients.forEach(item=>addIngredient({...item,convertLegacy:recipe.ingredientMode!=='perUnit',legacyOutputQty:recipe.outputQty}));updateRecipePreview();openModal('recipeModal')}
function deleteRecipe(id){if(!confirm('حذف وصفة التصنيع؟ سيبقى المنتج في المخزون.'))return;recipes=recipes.filter(item=>String(item.id)!==String(id));localStorage.setItem('cashtop_manufacturing_recipes',JSON.stringify(recipes));load()}
function openProduction(){$('productionRecipe').innerHTML='<option value="">اختر الوصفة...</option>'+recipes.map(recipe=>`<option value="${esc(recipe.id)}">${esc(pName(recipe.finishedProductId,recipe.finishedProductName))}</option>`).join('');$('batchCount').value='1';previewProduction();openModal('productionModal')}
function ingredientNeed(recipe,item,produced,batches){return recipe.ingredientMode==='perUnit'?num(item.qty)*produced:num(item.qty)*batches}
function previewProduction(){const recipe=recipes.find(item=>String(item.id)===String($('productionRecipe').value)),batches=num($('batchCount').value);if(!recipe||batches<=0){$('productionPreview').textContent='اختر وصفة التصنيع.';return}const produced=num(recipe.outputQty,1)*batches;const totals=recipeTotals(recipe);const lines=recipe.ingredients.map(item=>{const product=productById(item.productId),need=ingredientNeed(recipe,item,produced,batches),have=getQty(product,recipe.sourceWarehouseId||'shop');return`<div class="preview-line"><span>${esc(product?.name||item.name||'منتج محذوف')} — مطلوب ${precise(need)}</span><b class="${have+1e-9>=need?'success':'danger'}">متوفر ${precise(have)}</b></div>`}).join('');$('productionPreview').innerHTML=`<div class="preview-line"><span>الناتج</span><b>${esc(pName(recipe.finishedProductId,recipe.finishedProductName))} × ${precise(produced)}</b></div>${lines}<div class="preview-line"><span>تكلفة الأمر</span><b>${money(totals.total*batches)}</b></div><div class="preview-line"><span>الربح المتوقع</span><b>${money(totals.profit*batches)}</b></div>`}
function executeProduction(event){event.preventDefault();if(window.__mfgSaving)return;window.__mfgSaving=true;try{const recipe=recipes.find(item=>String(item.id)===String($('productionRecipe').value)),batches=num($('batchCount').value);if(!recipe||batches<=0)throw new Error('اختر وصفة وعدد دورات صحيح.');const produced=num(recipe.outputQty,1)*batches;const rows=recipe.ingredients.map(item=>({item,product:productById(item.productId),need:ingredientNeed(recipe,item,produced,batches)}));const shortage=rows.find(row=>!row.product||getQty(row.product,recipe.sourceWarehouseId||'shop')+1e-9<row.need);if(shortage)throw new Error(`المخزون غير كافٍ للمادة: ${shortage.product?.name||shortage.item.name||'محذوفة'}`);const finished=productById(recipe.finishedProductId);if(!finished)throw new Error('المنتج النهائي غير موجود. افتح الوصفة واحفظها من جديد.');const totals=recipeTotals(recipe),totalCost=totals.total*batches,destination=recipe.destinationWarehouseId||'shop',oldQty=getQty(finished,destination),oldCost=num(finished.cost);rows.forEach(row=>changeQty(row.product,recipe.sourceWarehouseId||'shop',-row.need));changeQty(finished,destination,produced);finished.cost=(oldQty+produced)>0?((oldQty*oldCost)+totalCost)/(oldQty+produced):totalCost/Math.max(.001,produced);finished.pricePiece=num(recipe.salePrice??finished.pricePiece);finished.price=finished.pricePiece;finished.updatedAt=new Date().toISOString();const revenue=num(finished.pricePiece)*produced;const order={id:`MFG_${Date.now()}_${Math.random().toString(36).slice(2,5)}`,branchId:branchId(),date:new Date().toISOString(),recipeId:recipe.id,productId:finished.id,productName:finished.name,batches,outputQty:produced,totalCost,unitCost:totalCost/Math.max(.001,produced),salePrice:num(finished.pricePiece),estimatedRevenue:revenue,estimatedProfit:revenue-totalCost,sourceWarehouseId:recipe.sourceWarehouseId||'shop',destinationWarehouseId:destination,status:'completed',ingredients:rows.map(row=>({productId:row.product.id,name:row.product.name,qty:row.need,cost:num(row.product.cost)}))};orders.push(order);const journal=readArray('cashtop_journal');journal.push({id:`J_${order.id}`,branchId:branchId(),date:order.date,type:'manufacturing',description:`تصنيع ${finished.name} بكمية ${precise(produced)}`,debit:totalCost,credit:totalCost,reference:order.id,nonCash:true});localStorage.setItem('cashtop_products',JSON.stringify(products));localStorage.setItem('cashtop_manufacturing_orders',JSON.stringify(orders));localStorage.setItem('cashtop_journal',JSON.stringify(journal));closeModal('productionModal');load();Cashtop.showToast('تم خصم المواد وإضافة المنتج المصنع وتحديث التكلفة والربح.','success')}catch(error){Cashtop.showToast(error.message||'تعذر تنفيذ التصنيع.','error')}finally{window.__mfgSaving=false}}
function renderAll(){const q=String($('searchInput')?.value||'').trim().toLowerCase();const filteredRecipes=recipes.filter(recipe=>!q||pName(recipe.finishedProductId,recipe.finishedProductName).toLowerCase().includes(q));const filteredOrders=orders.filter(order=>!q||String(order.id).toLowerCase().includes(q)||String(order.productName||'').toLowerCase().includes(q));$('recipesBody').innerHTML=filteredRecipes.length?filteredRecipes.map(recipe=>{const totals=recipeTotals(recipe),product=productById(recipe.finishedProductId);return`<tr><td><b>${esc(product?.name||recipe.finishedProductName||'منتج محذوف')}</b></td><td>${esc(product?.barcode||product?.pieceBarcode||recipe.finishedBarcode||'-')}</td><td>${precise(recipe.outputQty)}</td><td>${recipe.ingredients.map(item=>`${esc(pName(item.productId,item.name))} × ${precise(recipe.ingredientMode==='perUnit'?item.qty:num(item.qty)/Math.max(.001,num(recipe.outputQty,1)))}`).join('، ')}</td><td>${money(totals.unitCost)}</td><td>${money(totals.salePrice)}</td><td class="${totals.unitProfit>=0?'success':'danger'}">${money(totals.unitProfit)}</td><td><div class="actions"><button class="action-btn edit" onclick="editRecipe('${esc(recipe.id)}')"><i class="fa-solid fa-pen"></i></button><button class="action-btn delete" onclick="deleteRecipe('${esc(recipe.id)}')"><i class="fa-solid fa-trash"></i></button></div></td></tr>`}).join(''):'<tr><td colspan="8" style="padding:25px;color:#64748b">لا توجد وصفات تصنيع.</td></tr>';$('ordersBody').innerHTML=filteredOrders.length?filteredOrders.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(order=>`<tr><td>${esc(order.id)}</td><td>${new Date(order.date).toLocaleString('ar-EG')}</td><td><b>${esc(order.productName)}</b></td><td>${precise(order.outputQty)}</td><td>${money(order.totalCost)}</td><td>${money(order.estimatedRevenue)}</td><td class="${num(order.estimatedProfit)>=0?'success':'danger'}">${money(order.estimatedProfit)}</td><td><span class="badge badge-ok">مكتمل</span></td></tr>`).join(''):'<tr><td colspan="8" style="padding:25px;color:#64748b">لا توجد أوامر تصنيع.</td></tr>';const totalCost=orders.reduce((sum,order)=>sum+num(order.totalCost),0),profit=orders.reduce((sum,order)=>sum+num(order.estimatedProfit),0);$('statRecipes').textContent=recipes.length;$('statOrders').textContent=orders.length;$('statCost').textContent=money(totalCost);$('statProfit').textContent=money(profit)}
window.openRecipe=openRecipe;window.closeModal=closeModal;window.addIngredient=addIngredient;window.updateRecipePreview=updateRecipePreview;window.generateFinishedBarcode=generateFinishedBarcode;window.saveRecipe=saveRecipe;window.editRecipe=editRecipe;window.deleteRecipe=deleteRecipe;window.openProduction=openProduction;window.previewProduction=previewProduction;window.executeProduction=executeProduction;window.renderAll=renderAll;
window.addEventListener('load',()=>{bindAutocomplete($('finishedProductName'),$('finishedProductId'),$('finishedSuggestions'));load()});window.addEventListener('storage',event=>{if(!event.key||/cashtop_(products|stores|manufacturing)/.test(event.key))load()});window.addEventListener('cashtop:remote-applied',event=>{if(/cashtop_(products|stores|manufacturing)/.test(event.detail?.key||''))load()});document.addEventListener('click',event=>{if(!event.target.closest('.autocomplete'))closeSuggestions()});
})();
