(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const A=()=>window.OscarActivation;let databases=[],companies=[];
const safe=v=>String(v??'').trim(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const AI_MODEL_FALLBACKS=[
 {id:'google/gemini-2.5-flash:free',name:'Gemini 2.5 Flash :free — مجاني (المطلوب)',cost:0},
 {id:'openrouter/free',name:'OpenRouter Free Router — مجاني ومتوافق مع الصور',cost:0},
 {id:'openai/gpt-5.6-luna',name:'GPT-5.6 Luna — اقتصادي وسريع',cost:1.4},
 {id:'google/gemini-2.5-flash',name:'Gemini 2.5 Flash — اقتصادي',cost:2.8},
 {id:'google/gemini-2.5-pro',name:'Gemini 2.5 Pro — قوي',cost:11.25},
 {id:'openai/gpt-5.6-sol',name:'GPT-5.6 Sol — قوي جداً',cost:12},
 {id:'openai/gpt-5.6-sol-pro',name:'GPT-5.6 Sol Pro — أقوى reasoning',cost:12},
 {id:'openai/gpt-5.4',name:'GPT-5.4 — قوي جداً',cost:17.5},
 {id:'anthropic/claude-opus-5',name:'Claude Opus 5 — فئة قوية جداً',cost:30}
];
const pricePerM=v=>{const x=Number(v);return Number.isFinite(x)?x*1e6:Infinity};
function fillAIModels(models=[],selected=''){
 const sel=$('#aiModel');if(!sel)return;const current=selected||sel.value||'google/gemini-2.5-flash:free';
 const map=new Map(AI_MODEL_FALLBACKS.map(x=>[x.id,x]));
 for(const m of models){if(!m?.id)continue;const input=pricePerM(m.pricing?.prompt),output=pricePerM(m.pricing?.completion),cost=(Number.isFinite(input)?input:999999)+(Number.isFinite(output)?output:999999);map.set(m.id,{id:m.id,name:m.name||m.id,cost,input,output});}
 const arr=[...map.values()].sort((a,b)=>(a.cost??Infinity)-(b.cost??Infinity)||String(a.name).localeCompare(String(b.name),'ar'));
 sel.innerHTML=arr.map(m=>{const free=(m.cost===0)||(m.id.endsWith(':free'))||m.id==='openrouter/free';const price=free?'مجاني':(Number.isFinite(m.input)&&Number.isFinite(m.output)?`$${m.input.toFixed(3)} in / $${m.output.toFixed(3)} out لكل 1M`:m.cost<Infinity?'مدفوع':'السعر حسب المزود');return `<option value="${esc(m.id)}">${esc(m.name)} — ${esc(price)}</option>`}).join('');
 if(!map.has(current)){const o=document.createElement('option');o.value=current;o.textContent=current+' — محفوظ سابقاً';sel.prepend(o);} sel.value=current;
}
async function loadAIModels(selected=''){
 fillAIModels([],selected);const info=$('#aiModelInfo');if(info)info.textContent='جاري تحميل نماذج OpenRouter...';
 try{const r=await fetch('https://openrouter.ai/api/v1/models',{cache:'no-store'});const j=await r.json();fillAIModels(Array.isArray(j?.data)?j.data:[],selected);if(info)info.textContent='تم تحميل كل النماذج المتاحة وترتيبها حسب تكلفة الإدخال + الإخراج. المجاني أولاً.';}
 catch(_){if(info)info.textContent='تعذر تحديث القائمة؛ تم استخدام قائمة النماذج الأساسية المحفوظة.';}
}
const today=()=>new Date().toISOString().slice(0,10), uid=p=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
function toast(msg,type='ok'){const t=$('#toast');t.textContent=msg;t.className='toast show '+type;clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='toast',3600)}
function master(){const m=A().readMasterConfig();if(!m?.database?.databaseURL||!m?.database?.authToken)throw new Error('أدخل قاعدة البيانات الأم واحفظها أولاً.');return m}
function root(){return master().adminRootPath||'oscar/admin'}
function masterDb(){return master().database}
function modal(id,show=true){$(id).classList.toggle('show',show)}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-EG-u-nu-latn',{dateStyle:'medium'}).format(new Date(v))}catch(_){return v}}
function generateKey(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',part=()=>Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('');return`MZ-${part()}-${part()}`}
function resultRows(result){return A().tursoDirect.rows(result)}
async function listRecords(prefix){const rows=await A().tursoDirect.listPrefix(masterDb(),`${root()}/${prefix}`,{ensureSchema:true});return rows.filter(r=>!Number(r.deleted)).map(r=>r.payload).filter(Boolean)}
async function saveMaster(){const url=safe($('#masterUrl').value),token=safe($('#masterToken').value),aiApiKey=safe($('#aiApiKey').value),aiModel=safe($('#aiModel').value)||'google/gemini-2.5-flash:free';if(!url||!token)throw new Error('أدخل الرابط والتوكن.');if(!aiApiKey)throw new Error('أدخل مفتاح OpenRouter حتى ينزل داخل ملفات الشركات.');const cfg=A().saveMasterConfig({databaseURL:url,authToken:token,table:'oscar_rtdb',aiProvider:'openrouter',aiApiKey,aiModel});$('#masterStatus').textContent='جاري اختبار الاتصال...';await A().tursoDirect.ensure(cfg.database);$('#masterStatus').textContent='قاعدة الأم وCash Top AI محفوظان على جهاز الأدمن. أي ملف دخول جديد سيحمل إعدادات AI.';$('#masterStatus').className='status ok';await loadAll()}
async function loadAll(){const m=A().readMasterConfig();if(!m){databases=[];companies=[];render();return}$('#masterUrl').value=m.database.databaseURL||'';$('#masterToken').value=m.database.authToken||'';$('#aiApiKey').value=m.ai?.apiKey||'';$('#aiModel').value=m.ai?.model||'google/gemini-2.5-flash:free';$('#masterStatus').textContent=m.ai?.apiKey?'تم تحميل قاعدة الأم ومفتاح Cash Top AI من تخزين الأدمن.':'تم تحميل قاعدة الأم. أضف مفتاح OpenRouter حتى ينزل مع ملفات الشركات.';$('#masterStatus').className=m.ai?.apiKey?'status ok':'status';try{[databases,companies]=await Promise.all([listRecords('databases'),listRecords('companies')]);databases.sort((a,b)=>String(a.name).localeCompare(String(b.name),'ar'));companies.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));render()}catch(e){$('#masterStatus').textContent='تعذر قراءة القاعدة الأم: '+e.message;$('#masterStatus').className='status error';throw e}}
function render(){
 $('#statDatabases').textContent=databases.length;$('#statCompanies').textContent=companies.length;$('#statActive').textContent=companies.filter(x=>x.status==='active').length;$('#statStopped').textContent=companies.filter(x=>x.status!=='active').length;
 const count=id=>companies.filter(c=>c.databaseId===id).length;$('#databasesBody').innerHTML=databases.length?databases.map(d=>`<tr><td><b>${esc(d.name)}</b></td><td class="mono">${esc(d.id)}</td><td>${count(d.id)}</td><td>${fmt(d.updatedAt||d.createdAt)}</td><td><div class="actions"><button class="btn" data-edit-db="${d.id}">تعديل</button><button class="btn danger" data-delete-db="${d.id}" ${count(d.id)?'disabled':''}>حذف</button></div></td></tr>`).join(''):`<tr><td colspan="5" class="empty">لا توجد قواعد محفوظة.</td></tr>`;
 const options='<option value="">كل القواعد</option>'+databases.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join(''),filter=$('#companyDbFilter'),old=filter.value;filter.innerHTML=options;filter.value=old;
 const select=$('#companyForm select[name=databaseId]');select.innerHTML='<option value="">اختر القاعدة...</option>'+databases.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');
 renderCompanies()
}
function renderCompanies(){const filter=$('#companyDbFilter').value,list=companies.filter(c=>!filter||c.databaseId===filter);$('#companiesBody').innerHTML=list.length?list.map(c=>`<tr><td><b>${esc(c.companyName)}</b><br><small>${esc(c.id)}</small></td><td class="mono">${esc(c.companyKey)}</td><td>${esc(c.databaseName||databases.find(d=>d.id===c.databaseId)?.name||'—')}</td><td>${esc(c.manager?.name||'—')}</td><td>${c.plan==='lifetime'?'<span class="badge blue">مدى الحياة</span>':esc(c.plan||'pro')}</td><td><span class="badge ${c.status==='active'?'green':'red'}">${c.status==='active'?'نشط':'موقوف'}</span></td><td>${c.endAt?fmt(c.endAt):'مدى الحياة'}</td><td><button class="btn primary" data-download-company="${c.id}" ${c.status==='active'?'':'disabled'}>تحميل .mzauth</button></td><td><div class="actions"><button class="btn" data-edit-company="${c.id}">تعديل</button><button class="btn" data-renew-company="${c.id}">تجديد الملف</button><button class="btn ${c.status==='active'?'danger':'green'}" data-toggle-company="${c.id}">${c.status==='active'?'إيقاف':'تفعيل'}</button></div></td></tr>`).join(''):`<tr><td colspan="9" class="empty">لا توجد شركات ضمن هذا الاختيار.</td></tr>`}
async function databaseCredentials(id){const d=databases.find(x=>x.id===id);if(!d)throw new Error('قاعدة الشركة غير موجودة في السجل.');const m=master();const secret=m.database.authToken;const raw=await A().openObject(d.vault,secret);return{databaseURL:safe(raw.databaseURL),authToken:safe(raw.authToken),readAuthToken:safe(raw.readAuthToken),table:'oscar_rtdb'}}
function writeDatabaseConfig(raw){return{databaseURL:safe(raw?.databaseURL),authToken:safe(raw?.authToken),table:'oscar_rtdb'}}
function customerReadDatabaseConfig(raw){const readAuthToken=safe(raw?.readAuthToken);if(!readAuthToken)throw new Error('توكن القراءة فقط للعملاء غير مضبوط لهذه القاعدة. افتح القاعدة من الإدارة وأضف Read Only Token.');return{databaseURL:safe(raw?.databaseURL),authToken:readAuthToken,table:'oscar_rtdb'}}
async function publishCompany(company){const raw=await databaseCredentials(company.databaseId),db=writeDatabaseConfig(raw),access={companyId:company.id,tenantId:company.id,companyName:company.companyName,companyKey:company.companyKey,status:company.status,plan:company.plan,startAt:company.startAt,endAt:company.endAt||'',manager:company.manager,companyCreatedAt:company.createdAt||'',dataNamespaceVersion:2,customerPortalEnabled:!!raw.readAuthToken,updatedAt:Date.now()};await A().tursoDirect.writeExact(db,`oscar/companies/${encodeURIComponent(company.id)}/access/company`,access,Date.now(),false);return db}
async function saveCompanyRecord(company){company.updatedAt=new Date().toISOString();await A().tursoDirect.writeExact(masterDb(),`${root()}/companies/${company.id}`,company,Date.now(),false);return company}
async function upsertCompany(fd){const id=safe(fd.get('id'))||uid('CMP'),existing=companies.find(x=>x.id===id),databaseId=safe(fd.get('databaseId')),database=databases.find(x=>x.id===databaseId);if(!database)throw new Error('اختر قاعدة شركة مسجلة.');const key=safe(fd.get('companyKey')).toUpperCase();if(companies.some(x=>x.companyKey===key&&x.id!==id))throw new Error('مفتاح الشركة مستخدم لشركة أخرى.');const manager=existing?.manager?{...existing.manager}:{id:uid('MGR'),role:'مدير النظام',system:true,permissions:['*'],createdAt:new Date().toISOString(),authVersion:uid('AUTH')};manager.name=safe(fd.get('managerName'))||'مدير النظام';manager.displayName=manager.name;manager.active=true;const company={...existing,id,companyName:safe(fd.get('companyName')),companyKey:key,databaseId,databaseName:database.name,plan:safe(fd.get('plan'))||'lifetime',status:safe(fd.get('status'))||'active',startAt:safe(fd.get('startAt'))||today(),endAt:safe(fd.get('endAt')),manager,createdAt:existing?.createdAt||new Date().toISOString()};if(!existing){const raw=await databaseCredentials(databaseId),db=writeDatabaseConfig(raw);await A().tursoDirect.deletePrefix(db,`oscar/companies/${encodeURIComponent(id)}/d`);}await publishCompany(company);await saveCompanyRecord(company);await loadAll();return company}
async function downloadCompany(company,rotate=false){if(!company)throw new Error('الشركة غير موجودة.');const m=master(),ai={provider:m.ai?.provider||'openrouter',apiKey:safe(m.ai?.apiKey),model:safe(m.ai?.model)||'google/gemini-2.5-flash:free'};if(!ai.apiKey)throw new Error('أضف مفتاح OpenRouter في إعدادات الأدمن واحفظه أولاً.');const raw=await databaseCredentials(company.databaseId),db=writeDatabaseConfig(raw),customerDatabase=customerReadDatabaseConfig(raw);try{const remote=await A().tursoDirect.readExact(db,`oscar/companies/${encodeURIComponent(company.id)}/access/company`,{ensureSchema:true}),value=remote&&typeof remote==='object'&&Object.prototype.hasOwnProperty.call(remote,'v')?(remote.deleted?null:remote.v):remote;if(value?.manager?.id&&String(value.manager.id)===String(company.manager?.id||''))company.manager={...company.manager,...value.manager}}catch(_){}if(rotate){company.manager={...company.manager,authVersion:uid('AUTH'),updatedAt:new Date().toISOString()};await publishCompany(company);await saveCompanyRecord(company);await loadAll();company=companies.find(x=>x.id===company.id)}else await saveCompanyRecord(company);const payload={type:'company-manager',activationKey:company.companyKey,fileId:`manager_${company.manager.id}_${company.manager.authVersion}`,companyId:company.id,tenantId:company.id,companyKey:company.companyKey,companyName:company.companyName,status:company.status,plan:company.plan,startAt:company.startAt,expiresAt:company.endAt||'',companyCreatedAt:company.createdAt||'',dataNamespaceVersion:2,database:db,customerDatabase,ai,rootPath:'oscar/companies',account:{...company.manager,branchId:'BR-MAIN',permissions:[]}};await A().downloadActivationFile(payload,`${company.companyName}-مدير.mzauth`)}
async function saveDatabase(fd){const id=safe(fd.get('id'))||uid('DB'),existing=databases.find(x=>x.id===id),name=safe(fd.get('name')),databaseURL=safe(fd.get('databaseURL')),authToken=safe(fd.get('authToken')),readAuthToken=safe(fd.get('readAuthToken'));if(!name||!databaseURL||!authToken||!readAuthToken)throw new Error('أكمل رابط القاعدة وتوكن الكتابة وتوكن القراءة فقط للعملاء.');const cfg={databaseURL,authToken,table:'oscar_rtdb'};await A().tursoDirect.ensure(cfg);const readCfg={databaseURL,authToken:readAuthToken,table:'oscar_rtdb'};try{await A().tursoDirect.pipeline(readCfg,[{sql:'SELECT 1 AS ok',args:[]}],12000)}catch(e){throw new Error('تعذر التحقق من توكن القراءة فقط: '+(e?.message||e))}const vault=await A().sealObject({databaseURL,authToken,readAuthToken},masterDb().authToken),record={id,name,vault,hasCustomerReadToken:true,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await A().tursoDirect.writeExact(masterDb(),`${root()}/databases/${id}`,record);await loadAll();return record}
function openDatabase(d=null){const f=$('#databaseForm');f.reset();f.elements.id.value=d?.id||'';f.elements.name.value=d?.name||'';if(d){databaseCredentials(d.id).then(cfg=>{f.elements.databaseURL.value=cfg.databaseURL;f.elements.authToken.value=cfg.authToken;f.elements.readAuthToken.value=cfg.readAuthToken||''}).catch(e=>toast(e.message,'error'))}modal('#databaseModal',true)}
function openCompany(c=null){const f=$('#companyForm');f.reset();$('#companyModalTitle').textContent=c?'تعديل الشركة':'شركة جديدة';f.elements.id.value=c?.id||'';f.elements.companyName.value=c?.companyName||'';f.elements.companyKey.value=c?.companyKey||generateKey();f.elements.databaseId.value=c?.databaseId||'';f.elements.managerName.value=c?.manager?.name||'مدير النظام';f.elements.plan.value=c?.plan||'lifetime';f.elements.status.value=c?.status||'active';f.elements.startAt.value=(c?.startAt||today()).slice(0,10);f.elements.endAt.value=(c?.endAt||'').slice(0,10);modal('#companyModal',true)}
async function toggleCompany(id){const c=companies.find(x=>x.id===id);if(!c)return;c.status=c.status==='active'?'stopped':'active';await publishCompany(c);await saveCompanyRecord(c);await loadAll();toast(c.status==='active'?'تم تفعيل الشركة ونشر الحالة.':'تم إيقاف الشركة ونشر الحالة.','ok')}
async function deleteDatabase(id){if(companies.some(c=>c.databaseId===id))throw new Error('لا يمكن حذف قاعدة مرتبطة بشركات.');await A().tursoDirect.writeExact(masterDb(),`${root()}/databases/${id}`,{deleted:true,id},Date.now(),true);await loadAll()}
function bind(){
 $('#saveMaster').onclick=()=>saveMaster().then(()=>toast('تم حفظ قاعدة الأم وإعدادات Cash Top AI.')).catch(e=>toast(e.message,'error'));$('#clearMaster').onclick=()=>{A().clearMasterConfig();$('#masterUrl').value='';$('#masterToken').value='';$('#aiApiKey').value='';$('#aiModel').value='google/gemini-2.5-flash:free';databases=[];companies=[];render();$('#masterStatus').textContent='تم مسح بيانات قاعدة الأم وCash Top AI من هذا الجهاز.';$('#masterStatus').className='status'};$('#toggleAIKey').onclick=()=>{const i=$('#aiApiKey'),show=i.type==='password';i.type=show?'text':'password';$('#toggleAIKey').textContent=show?'إخفاء':'إظهار'};$('#refreshAIModels').onclick=()=>loadAIModels($('#aiModel').value).catch(()=>{});$('#refreshAll').onclick=()=>loadAll().then(()=>toast('تم تحديث السجل.')).catch(e=>toast(e.message,'error'));$('#addDatabase').onclick=()=>openDatabase();$('#addCompany').onclick=()=>openCompany();$('#companyDbFilter').onchange=renderCompanies;$('#generateCompanyKey').onclick=()=>$('#companyForm').elements.companyKey.value=generateKey();
 $$('[data-close]').forEach(b=>b.onclick=()=>modal('#'+b.closest('.modal-root').id,false));$$('.modal-root').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)modal('#'+m.id,false)}));
 $('#databaseForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;saveDatabase(new FormData(e.currentTarget)).then(()=>{modal('#databaseModal',false);toast('تم حفظ قاعدة الشركة وتشفير بياناتها.')}).catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};
 $('#companyForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;upsertCompany(new FormData(e.currentTarget)).then(()=>{modal('#companyModal',false);toast('تم حفظ الشركة ونشر مفتاحها إلى قاعدة الشركة.')}).catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const run=promise=>{b.disabled=true;promise.catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};if(b.dataset.editDb)openDatabase(databases.find(x=>x.id===b.dataset.editDb));if(b.dataset.deleteDb)run(deleteDatabase(b.dataset.deleteDb));if(b.dataset.editCompany)openCompany(companies.find(x=>x.id===b.dataset.editCompany));if(b.dataset.downloadCompany)run(downloadCompany(companies.find(x=>x.id===b.dataset.downloadCompany),false));if(b.dataset.renewCompany)run(downloadCompany(companies.find(x=>x.id===b.dataset.renewCompany),true));if(b.dataset.toggleCompany)run(toggleCompany(b.dataset.toggleCompany))});
 $$('[data-jump]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'});$$('[data-jump]').forEach(x=>x.classList.toggle('active',x===b))})
}
document.addEventListener('DOMContentLoaded',()=>{if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js?v=7.9.4.136-localization',{scope:'./',updateViaCache:'none'}).catch(()=>{});bind();const m=A().readMasterConfig();const selected=m?.ai?.model||'google/gemini-2.5-flash:free';loadAIModels(selected).catch(()=>{});if(m){$('#masterUrl').value=m.database.databaseURL||'';$('#masterToken').value=m.database.authToken||'';$('#aiApiKey').value=m.ai?.apiKey||'';loadAll().catch(e=>toast(e.message,'error'))}else render()});
})();
