(()=>{'use strict';
const cfg=window.CASHTOP_PUSH||{};
function b64ToUint8(value){const pad='='.repeat((4-value.length%4)%4),base=(value+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function registration(){if(!('serviceWorker'in navigator))throw new Error('Service Worker غير مدعوم');return navigator.serviceWorker.ready}
async function ensureSubscription(){if(!cfg.enabled)return{ok:false,message:'خدمة Push غير مفعلة'};if(!cfg.vapidPublicKey)return{ok:false,message:'يلزم ضبط VAPID Public Key في push-config.js لتفعيل إشعارات الخلفية العامة.'};if(Notification.permission!=='granted')return{ok:false,message:'صلاحية الإشعارات غير ممنوحة'};const reg=await registration();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(cfg.vapidPublicKey)});const endpoint=String(cfg.apiBase||'').replace(/\/$/,'')+'/subscribe';const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription:sub.toJSON(),scope:location.origin,userAgent:navigator.userAgent,companyId:(window.Cashtop?.companyIdFromSession?.()||window.Cashtop?.getSession?.()?.tenantId||''),role:(window.Cashtop?.getSession?.()?.role||''),userId:(window.Cashtop?.getSession?.()?.uid||window.Cashtop?.getSession?.()?.username||''),updatedAt:new Date().toISOString()})});if(!res.ok)throw new Error('تعذر تسجيل جهاز الإشعارات');return{ok:true,subscription:sub}}
async function requestAndSubscribe(){if(!('Notification'in window))return{ok:false,message:'المتصفح لا يدعم الإشعارات'};let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p!=='granted')return{ok:false,message:'تم رفض صلاحية الإشعارات. فعّلها من إعدادات المتصفح.'};if(!cfg.vapidPublicKey)return{ok:true,permissionOnly:true,message:'تم منح صلاحية الإشعارات المحلية. إشعارات Push العامة تحتاج ضبط VAPID.'};try{return await ensureSubscription()}catch(e){return{ok:false,message:e.message||'تعذر تفعيل Push'}}}
window.CashtopPush={ensureSubscription,requestAndSubscribe};
if('Notification'in window&&Notification.permission==='granted'){window.addEventListener('load',()=>ensureSubscription().catch(()=>null),{once:true});}
})();
