// Build a direct return as one atomic local batch. No artificial sale is created.
export function buildCartReturn({cart,products,stock,accounts,customers,settings,customer,user,shift,payload={},discountType,discountValue,id,now}) {
 const money=n=>Math.round(n*100)/100;
 const put=(storeName,value,before)=>({type:'put',storeName,value,before,actionHint:before?'update':'add'});
 if(!cart?.length)throw new Error('السلة فارغة');
 const warehouseId=settings.activeWarehouseId;if(!warehouseId)throw new Error('اختر المخزن');
 const items=cart.map(i=>{const p=products.find(p=>p.id===i.productId&&!p.deletedAt);const quantity=Number(i.quantity),unitPrice=Number(i.unitPrice),factor=Number(i.conversionFactor||i.availableUnits?.find(u=>u.id===i.unitId)?.conversionToBase||1);if(!p||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitPrice)||unitPrice<0||!Number.isFinite(factor)||factor<=0)throw new Error('تحقق من بيانات الصنف والكمية والسعر');const taxRate=Number(i.taxRate)||0;return {...i,quantity,unitPrice,conversionFactor:factor,baseQuantity:quantity*factor,total:money(quantity*unitPrice),taxRate,costPriceAtSale:Number(p.costPrice||0)*factor,fifoCostTotal:quantity*factor*Number(p.costPrice||0)}});
 const rawSubtotal=items.reduce((s,i)=>s+i.quantity*i.unitPrice,0),rawTax=items.reduce((s,i)=>s+i.quantity*i.unitPrice*i.taxRate/100,0),subtotal=money(rawSubtotal),taxTotal=money(rawTax);
 const before=money(rawSubtotal+rawTax),discountTotal=money(Math.min(before,discountType==='percent'?before*Math.max(0,Math.min(100,Number(discountValue)||0))/100:Math.max(0,Number(discountValue)||0)));
 const additionalCharges=Math.max(0,Number(payload.additionalCharges)||0);let grandTotal=money(before-discountTotal+additionalCharges);if(settings.scaleModeEnabled)grandTotal=Math.round(grandTotal);
 const accountRefunds=(payload.payments||[]).filter(p=>Number(p.amount)!==0).map(p=>{const a=accounts.find(a=>a.id===p.accountId&&!a.deletedAt);const amount=Number(p.amount);if(!a||!Number.isFinite(amount)||amount<0)throw new Error('حساب أو مبلغ الاسترداد غير صحيح');return {accountId:a.id,accountName:a.name,method:a.type||'cash',amount:money(amount)}});
 const paidAmount=money(accountRefunds.reduce((s,p)=>s+p.amount,0));if(paidAmount>grandTotal+.005)throw new Error('المبلغ المسترد أكبر من إجمالي المرتجع');
 const debtReversed=money(Math.max(0,grandTotal-paidAmount));const partner=customers.find(c=>c.id===customer?.id&&!c.deletedAt&&c.id!=='cust-walkin');if(debtReversed>0&&!partner)throw new Error('اختر عميلاً مسجلاً لإضافة قيمة المرتجع إلى حسابه');
 const invoice={id,invoiceNumber:`RET-${id.slice(-8)}`,type:'return',directReturn:true,date:now,createdAt:now,financialYearId:settings.activeFinancialYearId||'fy-initial',customerId:partner?.id||'cust-walkin',customerName:partner?.name||'عميل نقدي',cashierId:user.id,cashierName:user.name,warehouseId,branchId:settings.activeBranchId,shiftId:shift?.id,items,subtotal,taxTotal,discountTotal,additionalCharges,grandTotal,paidAmount,remainingAmount:0,changeAmount:0,paymentType:debtReversed?(paidAmount?'partial_reverse':'debt_reverse'):'refund',payments:accountRefunds,returnAllocation:{debtReversed,accountRefunds},notes:payload.notes||'',status:'completed',syncId:id,isSynced:false};
 const operations=[put('invoices',invoice)];const changedStock=new Map(),changedProducts=new Map();
 items.forEach((item,index)=>{const key=`${item.productId}:${warehouseId}`;const old=stock.find(s=>s.productId===item.productId&&s.warehouseId===warehouseId);const row=changedStock.get(key)||{...old,productId:item.productId,warehouseId,baseQuantity:Number(old?.baseQuantity)||0};row.baseQuantity+=item.baseQuantity;row.updatedAt=now;changedStock.set(key,row);
 operations.push(put('stock_movements',{id:`${id}-mov-${index}`,date:now,financialYearId:invoice.financialYearId,productId:item.productId,productName:item.productName,warehouseId,type:'sales_return',baseQuantityChange:item.baseQuantity,newBaseBalance:row.baseQuantity,unitName:item.unitName,quantityInUnit:item.quantity,conversionFactor:item.conversionFactor,referenceId:id,referenceType:'SALES_RETURN',userId:user.id,userName:user.name}));
 const original=products.find(p=>p.id===item.productId);const product=changedProducts.get(item.productId)||{...original,fifoBatches:[...(original.fifoBatches||[])]};product.fifoBatches.push({id:`${id}-batch-${index}`,purchaseId:id,warehouseId,receivedAt:now,unitCost:Number(original.costPrice)||0,remainingBaseQty:item.baseQuantity,reversalBatch:true,sourceReturnId:id});product.updatedAt=now;changedProducts.set(item.productId,product);
 });
 changedStock.forEach(row=>operations.push(put('stock',row,stock.find(s=>s.productId===row.productId&&s.warehouseId===warehouseId))));changedProducts.forEach(row=>operations.push(put('products',row,products.find(p=>p.id===row.id))));
 if(debtReversed){const balance=money(Number(partner.balance||0)-debtReversed);operations.push(put('customers',{...partner,balance},partner),put('partner_statements',{id:`${id}-statement`,date:now,type:'reversal',partnerType:'customer',partnerId:partner.id,partnerName:partner.name,referenceType:'SALES_RETURN',referenceId:id,referenceNumber:invoice.invoiceNumber,description:`مرتجع مباشر ${invoice.invoiceNumber}`,debit:0,credit:debtReversed,runningBalance:balance,isReversal:true}));}
 accounts.forEach(a=>{const amount=accountRefunds.filter(p=>p.accountId===a.id).reduce((s,p)=>s+p.amount,0);if(amount)operations.push(put('accounts',{...a,balance:money(Number(a.balance||0)-amount)},a))});
 const cashRefund=accountRefunds.filter(p=>p.method==='cash').reduce((s,p)=>s+p.amount,0);if(shift&&cashRefund)operations.push(put('shifts',{...shift,totalCashReturns:money(Number(shift.totalCashReturns||0)+cashRefund),expectedCash:money(Number(shift.expectedCash||0)-cashRefund)},shift));
 operations.push(put('audit_logs',{id:`${id}-audit`,date:now,financialYearId:invoice.financialYearId,type:'sales_return_reverse_entry',referenceId:id,amount:grandTotal,debtReversed,accountRefunds,userId:user.id,userName:user.name}));
 return {invoice,operations};
}
