(function(){
'use strict';
const SUPPORT_ROOT='cashTopExchange/cashTopSupport';
const IMAGE_STORAGE=Object.freeze({storageZone:'amanwar1',pullHost:'amanwar1.b-cdn.net',accessKey:'bd094c93-3387-44e5-8ee02b4ff7c3-f22d-4060',rootFolder:'cashtop-images',maxDimension:1600,maxSizeKB:850});
const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function safePart(value,fallback='item'){const clean=String(value||'').trim().replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'');return(clean||fallback).slice(0,90)}
function session(){return window.Cashtop?.getSession?.()||{}}
function parse(value,fallback={}){try{return JSON.parse(value)||fallback}catch(_){return fallback}}
function companyInfo(){const s=session();const settings=parse(localStorage.getItem('cashtop_settings')||'{}',{});const access=parse(localStorage.getItem('cashtop_company_access')||'{}',{});return{tenantId:String(s.tenantId||s.companyId||access.tenantId||access.companyId||''),companyKey:String(s.companyKey||access.companyKey||''),companyName:String(settings.companyName||access.companyName||s.companyName||'شركة غير مسماة'),username:String(s.username||''),displayName:String(s.displayName||s.username||''),role:String(s.role||'')}}
function canvasBlob(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('تعذر ضغط الصورة.')),'image/jpeg',quality))}
async function loadBitmap(file){if(typeof createImageBitmap==='function'){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch(_){}}return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('تعذر قراءة الصورة.'));reader.onload=()=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('تعذر فتح الصورة.'));img.src=reader.result};reader.readAsDataURL(file)})}
async function prepareImage(file){if(!(file instanceof Blob)||!String(file.type||'').startsWith('image/'))throw new Error('يوجد ملف غير صالح ضمن المرفقات.');const bitmap=await loadBitmap(file);const w=Number(bitmap.width||bitmap.naturalWidth||0),h=Number(bitmap.height||bitmap.naturalHeight||0);if(!w||!h)throw new Error('أبعاد إحدى الصور غير صالحة.');const ratio=Math.min(1,IMAGE_STORAGE.maxDimension/Math.max(w,h));let tw=Math.max(1,Math.round(w*ratio)),th=Math.max(1,Math.round(h*ratio));let best=null;try{for(let pass=0;pass<4;pass++){const canvas=document.createElement('canvas');canvas.width=tw;canvas.height=th;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('هذا الجهاز لا يدعم تجهيز الصور.');ctx.fillStyle='#fff';ctx.fillRect(0,0,tw,th);ctx.drawImage(bitmap,0,0,w,h,0,0,tw,th);for(let q=.88;q>=.32;q-=.08){const blob=await canvasBlob(canvas,q);if(!best||blob.size<best.size)best=blob;if(blob.size<=IMAGE_STORAGE.maxSizeKB*1024)return blob}tw=Math.max(320,Math.round(tw*.78));th=Math.max(240,Math.round(th*.78))}if(best)return best;throw new Error('تعذر ضغط الصورة.')}finally{try{bitmap.close?.()}catch(_){}}}
async function uploadImage(file,ticketId,index){const info=companyInfo();const blob=await prepareImage(file);const tenant=safePart(info.tenantId||'company','company');const unique=`${safePart(ticketId,'ticket')}_${String(index+1).padStart(2,'0')}_${Date.now()}_${Math.random().toString(36).slice(2,7)}.jpg`;const path=`${IMAGE_STORAGE.rootFolder}/${tenant}/support/${unique}`;const endpoint=`https://storage.bunnycdn.com/${IMAGE_STORAGE.storageZone}/${path.split('/').map(encodeURIComponent).join('/')}`;const response=await fetch(endpoint,{method:'PUT',headers:{AccessKey:IMAGE_STORAGE.accessKey,'Content-Type':'image/jpeg'},body:blob,cache:'no-store'});if(!response.ok)throw new Error(`تعذر رفع صورة المرفق (${response.status}).`);return{url:`https://${IMAGE_STORAGE.pullHost}/${path.split('/').map(encodeURIComponent).join('/')}`,path,sizeKB:Math.round(blob.size/102.4)/10,originalName:String(file.name||`image-${index+1}`)}}
async function saveTicket(ticket){const bridge=window.CashtopTursoBridge;if(!bridge?.writeNode)throw new Error('خدمة إرسال الدعم غير متاحة حالياً.');await bridge.ready?.();await bridge.writeNode(`${SUPPORT_ROOT}/tickets/${safePart(ticket.id,'ticket')}`,ticket,false);const verify=await bridge.readNode?.(`${SUPPORT_ROOT}/tickets/${safePart(ticket.id,'ticket')}`,{cache:false}).catch(()=>null);if(!verify||String(verify.id||'')!==String(ticket.id))throw new Error('لم يتم تأكيد وصول البلاغ. حاول مرة أخرى.');return true}
function setBusy(value,text=''){const btn=$('submitBtn'),spinner=$('loadingSpinner'),label=$('btnText');if(btn)btn.disabled=value;spinner?.classList.toggle('hidden',!value);if(label&&text)label.textContent=text}
function renderPreviews(){const host=$('imagePreviewContainer');if(!host)return;host.innerHTML='';Array.from($('fileUpload')?.files||[]).forEach(file=>{if(!String(file.type||'').startsWith('image/'))return;const box=document.createElement('div');box.className='support-preview';const img=document.createElement('img');const url=URL.createObjectURL(file);img.src=url;img.onload=()=>URL.revokeObjectURL(url);const cap=document.createElement('span');cap.textContent=file.name||'صورة';box.append(img,cap);host.appendChild(box)})}
async function submit(e){e.preventDefault();const description=String($('problemDesc')?.value||'').trim();if(!description)return window.Cashtop?.showToast?.('اكتب وصف المشكلة أولاً.','warning');if(navigator.onLine===false)return window.Cashtop?.showToast?.('إرسال الدعم يحتاج اتصالاً بالإنترنت لرفع الصور والبلاغ.','warning');const info=companyInfo();if(!info.tenantId)return window.Cashtop?.showToast?.('تعذر تحديد الشركة الحالية. أعد تسجيل الدخول.','error');const ticketId=`SUP_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;setBusy(true,'جاري رفع المرفقات...');try{const files=Array.from($('fileUpload')?.files||[]).filter(f=>String(f.type||'').startsWith('image/'));const images=[];for(let i=0;i<files.length;i++){setBusy(true,`رفع الصورة ${i+1} من ${files.length}...`);images.push(await uploadImage(files[i],ticketId,i));await sleep(15)}setBusy(true,'جاري إرسال المشكلة...');const now=new Date().toISOString();const ticket={id:ticketId,tenantId:info.tenantId,companyId:info.tenantId,companyKey:info.companyKey,companyName:info.companyName,username:info.username,displayName:info.displayName,role:info.role,description,images,createdAt:now,updatedAt:now,status:'new',source:'support.html'};await saveTicket(ticket);$('supportForm')?.reset();$('imagePreviewContainer').innerHTML='';const result=$('ticketResult');if(result){result.textContent=`تم إرسال المشكلة بنجاح. رقم البلاغ: ${ticketId}`;result.classList.add('show')}window.Cashtop?.showToast?.('تم إرسال المشكلة للدعم الفني بنجاح.','success',3200)}catch(error){console.error('[SUPPORT]',error);window.Cashtop?.showToast?.(error?.message||'تعذر إرسال المشكلة.','error',4200)}finally{setBusy(false,'إرسال المشكلة')}}
window.addEventListener('DOMContentLoaded',()=>{$('fileUpload')?.addEventListener('change',renderPreviews);$('supportForm')?.addEventListener('submit',submit)});
})();
