const n=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>n(v).toFixed(2);
export const statementHeaders=['#','التاريخ','الحركة','الوصف','مدين','دائن','الرصيد'];
export function customerStatementModel(customer,invoices=[],vouchers=[]){
 const events=[...invoices.filter(x=>x.customerId===customer.id&&!x.deletedAt).map(x=>({x,invoice:true})),...vouchers.filter(x=>x.partyType==='customer'&&x.partyId===customer.id&&!x.deletedAt).map(x=>({x,invoice:false}))].sort((a,b)=>(Date.parse(a.x.date)||0)-(Date.parse(b.x.date)||0)||String(a.x.id).localeCompare(String(b.x.id)));
 const entries=events.map(({x,invoice},i)=>{const returned=invoice&&x.type==='return';const debit=invoice?(returned?n(x.paidAmount):n(x.grandTotal)):(x.type==='payment'?n(x.amount):0);const credit=invoice?(returned?n(x.grandTotal):n(x.paidAmount)):(x.type==='receipt'?n(x.amount):0);const lines=invoice?[`فاتورة ${x.invoiceNumber||''}`,...(x.items||[]).map(it=>`${it.productName||''} | ${it.unitName||'-'} | ${n(it.quantity)} × ${money(it.unitPrice)} = ${money(it.total??n(it.quantity)*n(it.unitPrice))}`),...(n(x.discountTotal)?[`خصم الفاتورة: ${money(x.discountTotal)}`]:[]),...(n(x.taxTotal)?[`الضريبة: ${money(x.taxTotal)}`]:[]),...(n(x.additionalCharges)?[`تكلفة إضافية: ${money(x.additionalCharges)}`]:[]),...(x.notes?[x.notes]:[])]:[`سند ${x.voucherNumber||''}`,x.notes||''].filter(Boolean);return {id:(invoice?'invoice:':'voucher:')+x.id,index:i+1,date:x.date,type:invoice?(returned?'مرتجع مبيعات':'فاتورة مبيعات'):(x.type==='receipt'?'سند قبض':'سند صرف'),description:lines.join('\n'),debit,credit};});
 const totalDebit=entries.reduce((s,e)=>s+e.debit,0),totalCredit=entries.reduce((s,e)=>s+e.credit,0);const opening=n(customer.balance)-totalDebit+totalCredit;let balance=opening;for(const e of entries){balance+=e.debit-e.credit;e.balance=Math.round(balance*100)/100;}
 return {opening,entries,totalDebit,totalCredit,closing:n(customer.balance),rows:[['','', 'رصيد سابق','الرصيد قبل الحركات المعروضة', '', '',opening],...entries.map(e=>[e.index,new Date(e.date).toLocaleDateString('ar-EG'),e.type,e.description,e.debit,e.credit,e.balance]),['','','الإجمالي','',totalDebit,totalCredit,n(customer.balance)]]};
}
